import React from 'react'
import './Proyects.css'

const Proyects = () => {
  return (
    <div className='proyects'>
<div> <h1> todolist</h1>   <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> Widget de clima </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>   <h1> Selector de emojis </h1>   <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>   <h1> Biblioteca </h1>   <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> Buscador  </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>

<div> <h1> Modal </h1>   <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> Acortador de URLs </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>   <h1> Calculadora </h1>   <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>   <h1> Tiktok  </h1>   <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> Componente estilo Notion  </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> App Pokemon  </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> App Movies  </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>
<div>  <h1> E-comerce </h1>    <p>  Hi there! My name is Agustin, and I am passionate and enthusiastic about creating on the web! My interest in development began when I decided to create a small website for a personal project with standard templates. Not being able to achieve the level of detail that I had I mind, I decided to get into the programming world, and since moment i did, I loved it! I like to write clean, tidy and work hard, I am currently looking to work in a place that allows me to grow, learn and progress in web development.</p></div>


   
    </div>
  )
}

export default Proyects